package tarefa01;

import udp.bidirecional.*;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import javax.swing.JOptionPane;

public class ClienteForm extends javax.swing.JFrame {

    private final ClienteServidor app;

    public ClienteForm() {
        initComponents();

        this.setTitle("Cliente");
        this.setResizable(true);
        this.setLocationRelativeTo(null);

        app = new ClienteServidor(txtHistorico, 5000, 5001);
        app.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        btnData = new javax.swing.JButton();
        btnDataExtrnso = new javax.swing.JButton();
        btnHora = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensagemAniver = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnDias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente UDP");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mensagem");

        txtMensagem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensagemKeyReleased(evt);
            }
        });

        txtHistorico.setColumns(20);
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        btnData.setText("DATA");
        btnData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataActionPerformed(evt);
            }
        });

        btnDataExtrnso.setText("DATA EXT");
        btnDataExtrnso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataExtrnsoActionPerformed(evt);
            }
        });

        btnHora.setText("HORA");
        btnHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraActionPerformed(evt);
            }
        });

        txtMensagemAniver.setColumns(20);
        txtMensagemAniver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMensagemAniver.setRows(5);
        txtMensagemAniver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensagemAniverKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtMensagemAniver);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Consultar quantos anos");

        btnDias.setText("DIAS RESTANTES");
        btnDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDataExtrnso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDias)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDataExtrnso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensagemKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            app.enviar(txtMensagem.getText());
            txtMensagem.setText("");
            txtMensagem.requestFocus();

        }

    }//GEN-LAST:event_txtMensagemKeyReleased
    private boolean isAnoValido(String texto) {
        try {
            int ano = Integer.parseInt(texto);

            if (ano >= 1900 && ano <= 2100) {
                return true;
            } else {
                System.out.println("Ano fora do intervalo desejado: " + ano);
                return false;
            }
        } catch (NumberFormatException e) {
            System.out.println("Erro de formatação: " + e.getMessage());
            return false; // Se não for um número, não é um ano válido
        }
    }
    
    public static int calcularIdade(int anoNascimento) {
        int anoAtual = LocalDate.now().getYear();
        int idade = anoAtual - anoNascimento;
        return idade;
    }
    private void btnDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataActionPerformed
      app.enviar("DATA");
    }//GEN-LAST:event_btnDataActionPerformed

    private void btnDataExtrnsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataExtrnsoActionPerformed
      app.enviar("DATA2");       
    }//GEN-LAST:event_btnDataExtrnsoActionPerformed

    private void btnHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraActionPerformed
       app.enviar("HORA");
    }//GEN-LAST:event_btnHoraActionPerformed

    private void txtMensagemAniverKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensagemAniverKeyReleased
    /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
     String textoDigitado = txtMensagem.getText();
     
        // Verifica se o texto é um ano válido
        if (isAnoValido(textoDigitado)) {
            // Obtém a data atual
            LocalDate dataAtual = LocalDate.now();
            int textoDigitado2 = Integer.parseInt(textoDigitado);
            // Cria uma data de nascimento com o ano fornecido
            LocalDate dataNascimento = LocalDate.of(textoDigitado2, 1, 1); // Supomos o dia 1 e mês 1

            // Calcula a diferença entre as datas
            Period periodo = Period.between(dataNascimento, dataAtual);

            // Obtém a idade em anos
            int idade = periodo.getYears();    
            String idade2 = String.valueOf(idade);
            app.enviar("Você tem " + idade2 + " anos.");                     
            txtMensagem.setText("");
            txtMensagem.requestFocus();
        } else {
            // Exibe uma mensagem de erro ou lida com a entrada inválida de outra forma
            JOptionPane.showMessageDialog(this, "Digite um ano válido.");
            txtMensagem.setText("");
            txtMensagem.requestFocus();
        }
       
    
    }*/
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           String textoDigitado = txtMensagemAniver.getText();
           int anoNascimento = Integer.parseInt(textoDigitado);
           int idade = calcularIdade(anoNascimento);
           String texto = String.valueOf(idade);
          app.enviar(texto);          
        }
    }//GEN-LAST:event_txtMensagemAniverKeyReleased

    private void btnDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiasActionPerformed
      app.enviar("DIAS-RESTANTES"); // TODO add your handling code here:
    }//GEN-LAST:event_btnDiasActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnData;
    private javax.swing.JButton btnDataExtrnso;
    private javax.swing.JButton btnDias;
    private javax.swing.JButton btnHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextArea txtMensagemAniver;
    // End of variables declaration//GEN-END:variables
}
